language: python
python:
  - 3.6
  - 3.7
install:
  - pip install -e .
  - pip install -r requirements.txt
  - pip install pytest pytest-cov flake8
  - pip install coveralls
script:
  # stop the build if there are Python syntax errors or undefined names
  - flake8 . --builtins=d,minitf,numpy --count --exclude=tests --select=E901,E999,F821,F822,F823 --show-source --statistics
  - coverage run --source=minitf -m pytest tests/
after_success:
  - coveralls
notifications:
  email:
    on_success: change
    on_failure: change
deploy:
  provider: pypi
  user: guocuimi
  password:
    secure: pypi-AgEIcHlwaS5vcmcCJDZkNDMwMzZmLTU0ZTktNGEzNS1hMTk1LTEwYWE1ZGVlNjg3ZQACN3sicGVybWlzc2lvbnMiOiB7InByb2plY3RzIjogWyJtaW5pdGYiXX0sICJ2ZXJzaW9uIjogMX0AAAYgcRmj3EKq7VqS1CkeehXVLfvmzy9-Pgm_BSZUeMkRZUA
  on:
    tags: true